language: cpp
dist: xenial
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: osx
      compiler: gcc
      osx_image: xcode10.1
    - os: osx
      compiler: clang
      osx_image: xcode10.1
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      eval "${MATRIX_EVAL}"
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
      sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update -qq
      if [[ "$CC" == "gcc-8" ]]; then
        sudo apt-get install -yqq g++-8 libstdc++-8-dev
      fi
      if [[ "$CC" == "clang-7" ]]; then
        sudo apt-get install -yqq clang-7 libc++-7-dev libc++abi-7-dev
      fi
      sudo apt-get install -yqq libopencv-dev libopencv-highgui-dev libopencv-video-dev libopencv-imgproc-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavresample-dev libavutil-dev libswresample-dev libswscale-dev
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg opencv
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
script: make VERBOSE=1
