language: cpp
dist: xenial
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
       add-apt-repository -y ppa:jonathonf/ffmpeg-4
       add-apt-repository -y ppa:timsc/opencv-3.4
       add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
       add-apt-repository -y ppa:ubuntu-toolchain-r/test
       apt-get update -qq
       apt-get install -yqq g++-7 clang-7 libstdc++-7-dev libopencv-dev libopencv-core-dev libopencv-videoio-dev libopencv-imgcodecs-dev libopencv-imgproc-dev libopencv-shape-dev libopencv-highgui-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavresample-dev libavutil-dev libswresample-dev libswscale-dev
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg opencv
    fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX ..
script: make VERBOSE=1
